Repository postlund/pyatv, pull requests merged in 2020-03, with the labels that each got.

#458 MRP Power State support
  docs/_config.yml
  docs/development/control.md
  docs/development/listeners.md
  docs/development/power_management.md
  docs/documentation/atvremote.md
  docs/index.md
  pyatv/__main__.py
  pyatv/const.py
  pyatv/dmap/__init__.py
  pyatv/interface.py
  pyatv/mrp/__init__.py
  pyatv/mrp/messages.py
  pyatv/mrp/protocol.py
  tests/dmap/test_dmap_functional.py
  tests/mrp/fake_mrp_atv.py
  tests/mrp/test_mrp_functional.py
Labels: mrp

#479 Release 0.4.1a1
  CHANGES.md
  pyatv/const.py
Labels: release

#480 scan: Do not include pure AirPlay devices
  docs/documentation/concepts.md
  pyatv/__init__.py
  pyatv/conf.py
  tests/test_conf.py
  tests/test_scan.py
Labels: scanning

#481 if: Deprecate suspend and wakeup
  pyatv/dmap/__init__.py
  pyatv/mrp/__init__.py
  pyatv/support.py
Labels: deprecation

#483 cq: Move internal modules to support directory
  pyatv/__init__.py
  pyatv/airplay/__init__.py
  pyatv/airplay/pairing.py
  pyatv/conf.py
  pyatv/dmap/__init__.py
  pyatv/interface.py
  pyatv/mrp/__init__.py
  pyatv/support/__init__.py
  pyatv/support/cache.py
  pyatv/support/device_info.py
  pyatv/support/net.py
  pyatv/support/udns.py
  tests/airplay/test_airplay_auth.py
  tests/support/test_cache.py
  tests/support/test_device_info.py
  tests/support/test_support.py
  tests/support/test_udns.py
Labels: code quality

#486 cq: Handle invalid credentials
  pyatv/airplay/__init__.py
  pyatv/dmap/daap.py
  pyatv/mrp/srp.py
  tests/airplay/fake_airplay_device.py
  tests/common_functional_tests.py
  tests/dmap/test_dmap_functional.py
Labels: enhancement

#487 cq: Add typing hints to public interface
  pyatv/__init__.py
  pyatv/__main__.py
  pyatv/conf.py
  pyatv/convert.py
  pyatv/helpers.py
  pyatv/interface.py
Labels: enhancement

#490 mrp: Subscribe to volume updates
  pyatv/mrp/messages.py
Labels: mrp

#492 docs: Add API documentation
  docs/_config.yml
  docs/_layouts/template.html
  docs/api/pyatv.html
  docs/api/pyatv/conf.html
  docs/api/pyatv/const.html
  docs/api/pyatv/convert.html
  docs/api/pyatv/exceptions.html
  docs/api/pyatv/helpers.html
  docs/api/pyatv/interface.html
  docs/assets/css/hljs.css
  docs/assets/css/normalize.css
  docs/assets/css/pdoc.css
  docs/assets/css/sanitize.css
  docs/assets/css/style.scss
  docs/assets/js/highlight.9.12.0.min.js
  docs/pdoc_templates/config.mako
  docs/pdoc_templates/html.mako
  requirements_docs.txt
  scripts/api.py
  tox.ini
Labels: documentation

#493 docs: Clean up and improve documentation
  docs/_config.yml
  docs/api/pyatv.html
  docs/api/pyatv/conf.html
  docs/api/pyatv/const.html
  docs/api/pyatv/helpers.html
  docs/api/pyatv/interface.html
  docs/development/api_reference.md
  pyatv/__init__.py
  pyatv/conf.py
  pyatv/const.py
  pyatv/helpers.py
  pyatv/interface.py
  scripts/api.py
  scripts/features.py
  tests/fake_udns.py
Labels: documentation

#495 docs: Change domain to pyatv.dev
  README.md
  docs/_config.yml
Labels: documentation

#496 docs: Fix baseurl
  docs/_config.yml
Labels: documentation

#497 docs: Fix relative links
  docs/_layouts/template.html
Labels: bug

#501 docs: Add links to API reference
  docs/_includes/api
  docs/api/pyatv.html
  docs/api/pyatv/conf.html
  docs/api/pyatv/const.html
  docs/api/pyatv/convert.html
  docs/api/pyatv/exceptions.html
  docs/api/pyatv/helpers.html
  docs/api/pyatv/interface.html
  docs/development/airplay.md
  docs/development/control.md
  docs/development/device_info.md
  docs/development/features.md
  docs/development/listeners.md
  docs/development/metadata.md
  docs/development/power_management.md
  docs/development/scan_pair_and_connect.md
  docs/documentation/concepts.md
  docs/documentation/documentation.md
  docs/index.md
  docs/pdoc_templates/html.mako
Labels: documentation

#502 test: Migrate from asynctest to pytest-asyncio
  docs/api/pyatv/helpers.html
  examples/auto_connect.py
  pyatv/helpers.py
  requirements_test.txt
  tests/airplay/test_airplay_pair.py
  tests/dmap/test_pairing.py
  tests/fake_udns.py
  tests/support/test_support.py
  tests/support/test_udns.py
  tests/test_helpers.py
  tests/test_scan.py
Labels: test

#508 protobuf: Workaround for older versions
  pyatv/support/__init__.py
  setup.py
Labels: mrp

#509 mrp: Support volume control features
  pyatv/mrp/__init__.py
  pyatv/mrp/player_state.py
  tests/mrp/fake_mrp_atv.py
  tests/mrp/test_mrp_functional.py
Labels: mrp

#513 Release 0.5.0
  CHANGES.md
  docs/api/pyatv/const.html
  docs/support/migration.md
  pyatv/const.py
Labels: release

#520 tests: Break out state in MRP fake device
  pyatv/mrp/messages.py
  scripts/fake_device.py
  tests/mrp/fake_mrp_atv.py
Labels: mrp, test

#524 docs: Various minor updates
  CONTRIBUTORS.md
  README.md
  docs/_config.yml
  docs/api/pyatv.html
  docs/api/pyatv/conf.html
  docs/api/pyatv/convert.html
  docs/api/pyatv/helpers.html
  docs/api/pyatv/interface.html
  docs/assets/css/pdoc.css
  docs/development/development.md
  docs/documentation/atvproxy.md
  docs/index.md
  docs/pdoc_templates/config.mako
  docs/support/acknowledgements.md
Labels: documentation

#525 docs: Add edit link at bottom
  docs/_layouts/template.html
  docs/development/features.md
Labels: documentation

#526 gha: Remove push from trigger
  .github/workflows/tests.yml
Labels: environment

#527 docs: Fix typo in link
  docs/index.md
Labels: documentation

#528 scan: Remove non-breaking space
  docs/api/pyatv.html
  docs/index.md
  pyatv/__init__.py
  tests/test_scan.py
Labels: bug

#529 scripts: Add features to atvscript
  docs/api/pyatv/interface.html
  docs/documentation/atvscript.md
  pyatv/scripts/atvscript.py
  tests/scripts/test_atvscript.py
Labels: scripts

#532 docs: Update FAQ regarding AirPlay
  docs/support/faq.md
Labels: documentation

#535 mrp: Add tvOS 13.4 build number
  pyatv/support/device_info.py
Labels: mrp

#538 bug: Make pairing interface consistent
  pyatv/airplay/pairing.py
  pyatv/mrp/pairing.py
  tests/dmap/test_dmap_pair.py
  tests/mrp/test_mrp_auth.py
Labels: airplay, dmap, mrp

#540 docs: Exclude internal function
  docs/api/pyatv/interface.html
  pyatv/interface.py
Labels: documentation

#542 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: environment

#545 scan: Clean up pending service browsers
  docs/api/pyatv.html
  pyatv/__init__.py
  tests/zeroconf_stub.py
Labels: bug
