Repository postlund/pyatv, pull requests merged in 2020-05, with the labels that each got.

#641 tests: Fix minor pytest incompatibilities
  tests/support/test_support.py
Labels: code quality

#666 cq: Add dependabot config
  .dependabot/config.yml
Labels: code quality

#668 doc: Add black badge to README
  README.md
Labels: documentation

#670 atvproxy: Add tunnel support
  docs/documentation/atvproxy.md
  pyatv/scripts/__init__.py
  pyatv/scripts/atvproxy.py
Labels: feature, scripts

#674 Added information regarding playbackRate issue
  docs/support/faq.md
Labels: documentation
