Repository postlund/pyatv, pull requests merged in 2023-05, with the labels that each got.

#1975 Add listener interface to Audio for volume updates
  docs/api/pyatv/interface.html
  docs/development/listeners.md
  docs/documentation/atvscript.md
  pyatv/core/facade.py
  pyatv/interface.py
  pyatv/scripts/atvscript.py
  tests/core/test_facade.py
  tests/protocols/mrp/test_mrp_interface.py
Labels: raop

#2007 Release 0.12.0
  CHANGES.md
  pyatv/const.py
Labels: release

#2012 env: Install correct miniaudio on GHA
  chickn.yaml
  scripts/chickn.py
Labels: environment

#2010 raop: Support asyncio StreamReader when streaming
  docs/api/pyatv/interface.html
  docs/development/audio.md
  docs/development/listeners.md
  docs/development/stream.md
  pyatv/core/facade.py
  pyatv/interface.py
  pyatv/protocols/raop/__init__.py
  pyatv/protocols/raop/audio_source.py
Labels: feature, raop

#2015 gha: Fix building docker images
  .github/workflows/release.yml
  Dockerfile
Labels: bug
