Repository postlund/pyatv, pull requests merged in 2023-08, with the labels that each got.

#2119 mrp: Add some missing protobuf definitions
  pyatv/protocols/mrp/protobuf/NowPlayingPlayer.proto
  pyatv/protocols/mrp/protobuf/NowPlayingPlayer_pb2.py
  pyatv/protocols/mrp/protobuf/NowPlayingPlayer_pb2.pyi
  pyatv/protocols/mrp/protobuf/Origin.proto
  pyatv/protocols/mrp/protobuf/Origin_pb2.py
  pyatv/protocols/mrp/protobuf/Origin_pb2.pyi
  pyatv/protocols/mrp/protobuf/UpdateOutputDeviceMessage.proto
  pyatv/protocols/mrp/protobuf/UpdateOutputDeviceMessage_pb2.py
  pyatv/protocols/mrp/protobuf/UpdateOutputDeviceMessage_pb2.pyi
  pyatv/protocols/mrp/protobuf/UpdatePlayerPath.proto
  pyatv/protocols/mrp/protobuf/UpdatePlayerPath_pb2.py
  pyatv/protocols/mrp/protobuf/UpdatePlayerPath_pb2.pyi
  pyatv/protocols/mrp/protobuf/__init__.py
Labels: mrp

#2083 Rework zeroconf for unicast scanning
  base_versions.txt
  pyatv/core/scan.py
  requirements/requirements.txt
  tests/core/test_scan.py
Labels: scanning

#2121 Release 0.13.3
  CHANGES.md
  pyatv/const.py
Labels: release

#2120 gha: Remove log workflow
  .github/workflows/log.yaml
Labels: environment

#2127 Release 0.13.4
  CHANGES.md
  docs/api/pyatv.html
  pyatv/const.py
Labels: release
